data_source dbsource:  
    type: snowflake
    account: cl31586.central-india.azure
    username: Hemachandran07
    password: es5817@Expleo
    role: accountadmin
    database: SNOWFLAKE_SAMPLE_DATA
    warehouse: compute_wh
    schema: TPCH_SF10
    threads: 10
    client_session_keep_alive: False
soda_cloud:
  host: cloud.soda.io
  api_key_id: 3f32c303-54d7-468a-835e-8248ec1739cd
  api_key_secret: -JWZB35t251nhyZehaRVVbu9DHhz8DtTSyDVsO8RbOSvy9RZWr9MtQ 
